//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Common.AutomationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PostItemServiceSoap", Namespace="http://Baridsoft.ir/")]
    public partial class PostItemService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendPostItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindPersonalNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PostItemService() {
            this.Url = global::Common.Properties.Settings.Default.Common_AutomationService_PostItemService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendPostItemCompletedEventHandler SendPostItemCompleted;
        
        /// <remarks/>
        public event FindPersonalNoCompletedEventHandler FindPersonalNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Baridsoft.ir/SendPostItem", RequestNamespace="http://Baridsoft.ir/", ResponseNamespace="http://Baridsoft.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendPostItemType SendPostItem(string userName, string passWord, PostItem postItem) {
            object[] results = this.Invoke("SendPostItem", new object[] {
                        userName,
                        passWord,
                        postItem});
            return ((SendPostItemType)(results[0]));
        }
        
        /// <remarks/>
        public void SendPostItemAsync(string userName, string passWord, PostItem postItem) {
            this.SendPostItemAsync(userName, passWord, postItem, null);
        }
        
        /// <remarks/>
        public void SendPostItemAsync(string userName, string passWord, PostItem postItem, object userState) {
            if ((this.SendPostItemOperationCompleted == null)) {
                this.SendPostItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPostItemOperationCompleted);
            }
            this.InvokeAsync("SendPostItem", new object[] {
                        userName,
                        passWord,
                        postItem}, this.SendPostItemOperationCompleted, userState);
        }
        
        private void OnSendPostItemOperationCompleted(object arg) {
            if ((this.SendPostItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPostItemCompleted(this, new SendPostItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Baridsoft.ir/FindPersonalNo", RequestNamespace="http://Baridsoft.ir/", ResponseNamespace="http://Baridsoft.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Participant FindPersonalNo(string userName, string passWord, string personalNo) {
            object[] results = this.Invoke("FindPersonalNo", new object[] {
                        userName,
                        passWord,
                        personalNo});
            return ((Participant)(results[0]));
        }
        
        /// <remarks/>
        public void FindPersonalNoAsync(string userName, string passWord, string personalNo) {
            this.FindPersonalNoAsync(userName, passWord, personalNo, null);
        }
        
        /// <remarks/>
        public void FindPersonalNoAsync(string userName, string passWord, string personalNo, object userState) {
            if ((this.FindPersonalNoOperationCompleted == null)) {
                this.FindPersonalNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindPersonalNoOperationCompleted);
            }
            this.InvokeAsync("FindPersonalNo", new object[] {
                        userName,
                        passWord,
                        personalNo}, this.FindPersonalNoOperationCompleted, userState);
        }
        
        private void OnFindPersonalNoOperationCompleted(object arg) {
            if ((this.FindPersonalNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindPersonalNoCompleted(this, new FindPersonalNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public partial class PostItem {
        
        private Attachment[] attachmentListField;
        
        private InvolvedPerson[] involvedPersonListField;
        
        private ImportanceType importanceTypeField;
        
        private string descriptionField;
        
        private string subjectField;
        
        private bool hasAttachmentField;
        
        /// <remarks/>
        public Attachment[] AttachmentList {
            get {
                return this.attachmentListField;
            }
            set {
                this.attachmentListField = value;
            }
        }
        
        /// <remarks/>
        public InvolvedPerson[] InvolvedPersonList {
            get {
                return this.involvedPersonListField;
            }
            set {
                this.involvedPersonListField = value;
            }
        }
        
        /// <remarks/>
        public ImportanceType ImportanceType {
            get {
                return this.importanceTypeField;
            }
            set {
                this.importanceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public bool HasAttachment {
            get {
                return this.hasAttachmentField;
            }
            set {
                this.hasAttachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public partial class Attachment {
        
        private string fileExtentionField;
        
        private string fileNameField;
        
        private decimal idField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        public string FileExtention {
            get {
                return this.fileExtentionField;
            }
            set {
                this.fileExtentionField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public partial class Participant {
        
        private decimal idField;
        
        private string displayStringField;
        
        private string organizationUnitField;
        
        private string personNameField;
        
        private string positionField;
        
        /// <remarks/>
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayString {
            get {
                return this.displayStringField;
            }
            set {
                this.displayStringField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationUnit {
            get {
                return this.organizationUnitField;
            }
            set {
                this.organizationUnitField = value;
            }
        }
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public partial class InvolvedPerson {
        
        private decimal organizationIDField;
        
        private string displayStringField;
        
        private string personNameField;
        
        private decimal personIDField;
        
        private string organizationUnitNameField;
        
        private string positionNameField;
        
        private decimal idField;
        
        private string descriptionField;
        
        private decimal involvedParticipantIDField;
        
        private InvolvedType involvedTypeField;
        
        /// <remarks/>
        public decimal OrganizationID {
            get {
                return this.organizationIDField;
            }
            set {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayString {
            get {
                return this.displayStringField;
            }
            set {
                this.displayStringField = value;
            }
        }
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationUnitName {
            get {
                return this.organizationUnitNameField;
            }
            set {
                this.organizationUnitNameField = value;
            }
        }
        
        /// <remarks/>
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal InvolvedParticipantID {
            get {
                return this.involvedParticipantIDField;
            }
            set {
                this.involvedParticipantIDField = value;
            }
        }
        
        /// <remarks/>
        public InvolvedType InvolvedType {
            get {
                return this.involvedTypeField;
            }
            set {
                this.involvedTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public enum InvolvedType {
        
        /// <remarks/>
        MainReceiver,
        
        /// <remarks/>
        CopyReceiver,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public enum ImportanceType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Fast,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Baridsoft.ir/")]
    public enum SendPostItemType {
        
        /// <remarks/>
        SendSuccessful,
        
        /// <remarks/>
        SendFaild,
        
        /// <remarks/>
        LoginFaild,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendPostItemCompletedEventHandler(object sender, SendPostItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPostItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPostItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendPostItemType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendPostItemType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FindPersonalNoCompletedEventHandler(object sender, FindPersonalNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindPersonalNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindPersonalNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Participant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Participant)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591